name: Enhancement
description: Suggest a way to improve our code or mod in general
labels: [ "enhancement" ]
assignees: ThatsNotM3
body:
    -   type: textarea
        attributes:
            label: Describe your Suggestion
            description: This part can definitely benefit from optimisations here and there...
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Proposed Changes
            description: Provide your solution and ideas on how to improve.
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Behaviour
            description: Describe current and expected behaviour, if needed.
        validations:
            required: false
    -   type: textarea
        attributes:
            label: Additional context
            description: Add any other context or screenshots about the suggestion here.
        validations:
            required: false
